### ISSUE TITLE
NetworkUtils, incorrect bit manipulation

### ISSUE THREAD

**Issue by flurbi** [jitsi/ice4j#100]
org.ice4j.ice.NetworkUtils.isLinkLocalIPv4Address(...)
        line 120
        incorrect: (address[1] & 0xFF) >= 16 && address[1] <= 31)
        problem  : address[1] may be negative
        correct  : (address[1] & 0xF0) == 0x10

**Comment by bgrozev** [comment]
Nice catch! Would you like to open a pull request (you'll have to sign our CLA (https://jitsi.org/icla or https://jitsi.org/ccla))?

**Comment by bgrozev** [comment]
FYI: I notice that the line numbers that you report do not match the lines in master (it's not really a problem for us as finding the actual lines is easy).

**Comment by saghul** [comment]
@bgrozev I'm 97.8% sure it's a bot.

**Comment by ibauersachs** [comment]
NetworkUtils is in libjitsi too. Please make sure any changes are synchronized.

Also this method name is wrong. Link local means addresses are not routed, which applies to the 169.254.0.0/16 range, but not to the RFC 1918 private network addresses.

@saghul: why?

**Comment by flurbi** [comment]
I also thought that `isPrivateIPv4Address` would be a better name, see https://en.wikipedia.org/wiki/Private_network.

**Comment by flurbi** [comment]
@saghul I passed the inverse Turing test. Never achieved this before, thank you ;-)

**Comment by saghul** [comment]
Heh, I've run into similar situations before and it always turned to be a bot :-) 

- relatively inactive GitHub account
- reports that look generated by some static analysis tool

I'm happy to be wrong, hi there fellow human!

**Comment by bgrozev** [comment]
@flurbi to clarify: should we expect PRs from you?

**Comment by bgrozev** [comment]
Re: the rest of the open issues -- we'll get there, we're just a bit swamped right now.

**Comment by flurbi** [comment]
@bgrozev My task was to review some libraries, I prefer not to write any PR. I assume it is a trivial matter for someone already involved in the project.

**Comment by bgrozev** [comment]
This is quite a mess. We have this method in three places, with the same bug and the same wrong name. Only one of them is used, as far as I can tell (TestNetworkAddressManagerService.java), and the intended semantics (link local or site local) are unclear. Whatever the semantics, it is not needed because of InetAddress#isLinkLocalAddress and InetAddress#isSiteLocalAddress.

I'll just remove all occurrences, and use my best guess for the intended semantics in TestNetworkAddressManagerService.java.
