### ISSUE TITLE
NetworkUtils, incorrect port range computation

### ISSUE THREAD

**Issue by flurbi** [jitsi/ice4j#101]
org.ice4j.ice.NetworkUtils.getRandomPortNumber(...)
        line 159
        incorrect: portNumberGenerator.nextInt(max - min) + min;
        correct  : portNumberGenerator.nextInt(max + 1 - min) + min;
        Also consider using SecureRandom instead of Random.

**Comment by bgrozev** [comment]
Fixed with https://github.com/jitsi/ice4j/pull/107
