### ISSUE TITLE
Running multiple PseudoTCP Sockets on top of a single MultiplexingSocket

### ISSUE THREAD

**Issue by JesusMcCloud** [jitsi/ice4j#109]
Hi!

Is it safe to run multiple PseudoTCP sockets on top of multiplexed sockets created from a single multiplexing socket?

**Comment by bgrozev** [comment]
I don't think anyone has tried doing this, so I can't confirm with certainty, but I don't see any reason why it wouldn't be "safe", provided that you set up for filtering in a reliable way (and assuming that you have a single PseudoTCP socket for each multiplexed socket). @paweldomas might have more insight.
