### ISSUE TITLE
Connection Data ("c=")

### ISSUE THREAD

**Issue by sante85** [jitsi/ice4j#128]
RFC format is c=
but in IceSdpUtils at line 179

mediaDescription.setConnection(sdpFactory.createConnection(
"IN", defaultAddress.getHostAddress(), addressFamily));

fix is exchange parameters:
mediaDescription.setConnection(sdpFactory.createConnection(
"IN", addressFamily, defaultAddress.getHostAddress()));

https://tools.ietf.org/html/rfc4566

Best regards

**Comment by imReker** [comment]
Commited in #136
