### ISSUE TITLE
Could i only this lib to communicate with web client by webRTC?

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [jitsi/ice4j#145]
I want to transmit audio & video data to web client by webRTC, these audio & video data are created by ffmpeg at server side.
Could i only use you guys' lib to finished it?Or maybe i only could use this lib as a ice server, and i need to use jni to invoke native PeerConnection, then connect to web client and transmit data by native PeerConnection.

**Comment by bgrozev** [comment]
ice4j is compatible with WebRTC. Note that it does only ICE, not DTLS (which you'd have to do on your own)

**Comment by BeiKeJieDeLiuLangMao** [comment]
👌Thank you! @bgrozev
