### ISSUE TITLE
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS and domain name

### ISSUE THREAD

**Issue by paolomeraviglia** [jitsi/ice4j#174]
Hi all
My server has public ip and is behind a nat. I have a dynamic dns service enabled, but inserting in org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS the domain causes problems with video/audio (disconnections every 30 secs).

Is there an option similar to NAT_HARVESTER_PUBLIC_ADDRESS that can resolve a domain name?

**Comment by damencho** [comment]
You can use: org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES

Please use the community forum for questions and problems.
