### ISSUE TITLE
How to use jitsi-videobridge as ICE Server?

### ISSUE THREAD

**Issue by chisijun** [jitsi/ice4j#189]
> can I use ice4j library for run server?

Yes, [jitsi-videobridge](https://github.com/jitsi/jitsi-videobridge) is one example.

_Originally posted by @bgrozev in https://github.com/jitsi/ice4j/issues/127#issuecomment-363830809_

i can used ice4j as ice client，but how used ice4j as ice server，I checked jitsi-videobridge, but I don't know how to use it.

**Comment by damencho** [comment]
Please, when having questions use the community forum before opening new issues.
