### ISSUE TITLE
NPE in MediaDescription#setAttribute() because CandidateAttribute#attribute is null

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jitsi/ice4j#19]
```
What steps will reproduce the problem?
- Create Agent and add audio stream, likle in test/ICE.java
- call IceSdpUtils#initSessionDescription()
- get 1st MediaDescription from new SessionDescription
- call MediaDescription.setAttribute("foo", "bar");

    Exception in thread "main" java.lang.NullPointerException
    	at gov.nist.javax.sdp.MediaDescriptionImpl.setAttribute(MediaDescriptionImpl.java:505)

What version of the product are you using? On what operating system?
r360

```

Original issue reported on code.google.com by `basini...@gmail.com` on 5 Nov 2013 at 1:13

**Comment by lyubomir** [comment]
Thank you for the contribution! Commit 26200eab218900ebf5dcd1ef5a0abd33883a49bc should fix this issue. I found your solution to be incomplete in terms of the value returned by CandidateAttribute.getAttribute().getValue() being different than the return value of CandidateAttribute.getValue() so I had to roll up my own.
