### ISSUE TITLE
About spurious wake-up in keepalive thread

### ISSUE THREAD

**Issue by dingdongnigetou** [jitsi/ice4j#199]
-File: StunCandidateHarvest.java
-Funcation: runInSendKeepAliveMessageThread
-Code:  
```c
if (timeout > 0)  {
                try
                {
                    sendKeepAliveMessageSyncRoot.wait(timeout);
                }
                catch (InterruptedException iex)
                {
                }
                /*
                 * Apart from being the time to send the STUN keep-alive
                 * message, it could be that we've experienced a spurious
                 * wake-up or that we've been canceled.
                 */
                return true;
}
```

My question is:

Why don't we change the if into while and recalculate the timeout value to fix the spurious wake-up issue here ? (I did this and testing is pass) Something I have missed ? 

If we just return ture here, then means we never send keepalive message to server side. 
So that server side will close the channel after timeout...

**Comment by bgrozev** [comment]
> If we just return ture here, then means we never send keepalive message to server side.

No, as the method's doc says returning `true` means that the method should be invoked again (resulting in the timeout being re-calculated as you suggest. And indeed [this is how it's used.](https://github.com/jitsi/ice4j/blob/master/src/main/java/org/ice4j/ice/harvest/StunCandidateHarvest.java#L1462)

**Comment by dingdongnigetou** [comment]
Hello bgrozev,

Thanks for your reply.

We can find out that the `sendKeepAliveMessageTime` value only will be [set](https://github.com/jitsi/ice4j/blob/e90c796d6d3184a7faf4a997465ce5d21e4cd809/src/main/java/org/ice4j/ice/harvest/StunCandidateHarvest.java#L1176) if we do not return ture.

So in the next round, the `sendKeepAliveMessageTime` still is -1, so that the `timeout` seams never being re-calculated.

And server side can not see any REFRESH method from the client during my testing, util i changed the code as i said before.
