### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by UweSauter** [jitsi/ice4j#200]
Running on Debian 10 with OpenJDK 11.0.6 and jicofo 1.0-544-1 I get the following in the jicofo.log file:

```
Jicofo 2020-04-16 07:51:25.558 INFO: [21] org.jitsi.jicofo.ComponentsDiscovery.log() Services re-discovery interval: 30000                                                                              
Jicofo 2020-04-16 07:51:25.560 INFO: [21] org.jitsi.jicofo.FocusManager.log() XMPP provider reg state: RegistrationState=Registered                                                                     
Jicofo 2020-04-16 07:51:25.575 INFO: [21] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect().305 XMPP provider Jabber:focus@auth.MYHOST/focus8887678906@localhost connected (JID: focus@auth.MYHOST/focus8887678906)
Jicofo 2020-04-16 07:51:26.271 INFO: [14] org.eclipse.jetty.server.handler.ContextHandler.doStart() Started o.e.j.s.ServletContextHandler@79dc1fe6{/,null,AVAILABLE}                                    
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.ice4j.socket.jdk8.DelegatingServerSocketChannel (file:/usr/share/jicofo/lib/ice4j-3.0-10-g982e782.jar) to method sun.nio.ch.SelChImpl.translateInterestOps(int)
WARNING: Please consider reporting this to the maintainers of org.ice4j.socket.jdk8.DelegatingServerSocketChannel                                                                                       
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations                                                                                                   
WARNING: All illegal access operations will be denied in a future release
Jicofo 2020-04-16 07:51:26.418 INFO: [14] org.eclipse.jetty.server.AbstractConnector.doStart() Started MuxServerConnector@13ec17de{HTTP/1.1,[http/1.1]}{0.0.0.0:8888}                                   
Jicofo 2020-04-16 07:51:26.420 INFO: [14] org.eclipse.jetty.server.Server.doStart() Started @6534ms
```

Don't think this is a problem (yet?) but thougth I'll let you know as suggested by the warning.

Edit: replaced hostname with MYHOST

**Comment by bgrozev** [comment]
Thanks for the report.

We just [removed MuxServerConnector](https://github.com/jitsi/jicoco/pull/78), so this particular error should not appear with tip of master in jicofo.

**Comment by kuerbis42** [comment]
Running on Debian 10, just installed 06.Jan. 2021

`Jicofo 2021-01-06 16:36:05.218 INFORMATION: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.jicofo.BRIDGE_MUC=JvbBrewery@internal.auth._mydomain_.com

Jicofo 2021-01-06 16:36:05.222 INFORMATION: [13] org.jitsi.jicofo.health.Health.log() Health checks are disabled.

Jicofo 2021-01-06 16:36:05.224 INFORMATION: [1] java.util.prefs.run() Created user preferences directory.

Jicofo 2021-01-06 16:36:05.228 INFORMATION: [1] org.jitsi.xmpp.component.ComponentBase.log() Component org.jitsi.jicofo. config:
....
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/usr/share/jicofo/lib/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`

Thx.  I'll let you know as suggested by the warning.

**Comment by Francewhoa** [comment]
We face the same challenge here

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.util.SecureAction (file:/usr/share/jitsi/lib/felix.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.util.SecureAction
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Using
* jitsi_2.10.5550-1_amd64.deb
* Debian 10 Buster
* GNOME 3.30.2
* Wayland

**Comment by Francewhoa** [comment]
For those considering using Jitsi Desktop, as of July 2022, I suggest considering this :
1. **Outdated**
Jitsi Desktop last version was released in 2017. Which is 5 years ago.
Source : https://community.jitsi.org/t/jitsi-users-jitsi-desktop-2-10-released/12014 or at https://archive.ph/v9otp

3. **Unsecured**
Jitsi Desktop from 2017 depends on Java version 8. Which was released in 2014. It's extended support ends between 2022 and 2030. Depending on which supplier you choose. After this, it will no longer be secure. 
Source https://en.wikipedia.org/wiki/Java_version_history or at https://archive.ph/oXOT1#selection-747.4-783.4

**Comment by saghul** [comment]
FTR, ice4j is a library used by multiple projects, and none of the above applies to jicofo.

**Comment by Francewhoa** [comment]
Thanks @saghul :) I missed that this ticket is about jicofo. My bad.

I searched for the error message and found this ticket
