### ISSUE TITLE
ice4j unmaintained on Maven repo

### ISSUE THREAD

**Issue by darrencocco** [jitsi/ice4j#213]
Many other libs under org.jitsi seem to be recently update in the Maven central repo but this project hasn't been updated there since 1.0.

Is this a policy decision or just an oversight by the maintainer or developers?

If it is just an oversight I would greatly appreciate it if you could start updating it again, thanks.

**Comment by bgrozev** [comment]
We would like to publish new versions to maven central, but we now have dependencies (jitsi-utils, jitsi-metaconfig)  that we have to publish first, and we haven't gotten to doing that yet.

**Comment by ibauersachs** [comment]
@bgrozev I published -utils and now -metaconfig as well on Central. I tried to publish ice4j again as well, but, what the hell... why and how did Jitsi-specific config readers (jicoco-config) end up in here? ice4j isn't (or now probably: wasn't) just used by Jitsi.

**Comment by bbaldino** [comment]
@ibauersachs not sure if I'm understanding the issue right, but, `jicoco-config` has some common helpers on top of `jitsi-metaconfig` for applications which are transitioning from `sip-communicator.properties` to a new-style config file, so that's why ice4j uses jicoco-config.

**Comment by ibauersachs** [comment]
@bbaldino ice4j never used a sip-communicator.properties (afaik at least), but just plain, old Java system properties. JiCoCo has a massive dependency chain because it just keeps accumulating "stuff". This shouldn't be pulled into a library with a very dedicated purpose.

**Comment by JonathanLennox** [comment]
jicoco-config isn't the whole of jicoco.  This is all that `mvn dependency:tree` shows for it:

```
[INFO] +- org.jitsi:jicoco-config:jar:1.1-53-gdc63c67:compile
[INFO] |  +- org.jitsi:jitsi-metaconfig:jar:c3d8c51747:compile
[INFO] |  +- com.typesafe:config:jar:1.3.4:compile
[INFO] |  +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.3.72:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.3.72:compile
[INFO] |  |  |  \- org.jetbrains:annotations:jar:13.0:compile
[INFO] |  |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.3.72:compile
[INFO] |  \- org.jetbrains.kotlin:kotlin-reflect:jar:1.3.72:compile
```

**Comment by ibauersachs** [comment]
Right, missed that. Wouldn't that be better named `jitsi-config` then and live in a separate repo?

(And it's still a shame that ice4j needs Kotlin for a handful of config properties. I don't mind Kotlin, but for only this it's a lot.)

**Comment by bbaldino** [comment]
`jitsi-config` isn't really much code, so we wanted to avoid a separate repo and just do another artifact (in general I don't think we're looking to create more repos right now as they're getting a bit tiresome).

**Comment by ibauersachs** [comment]
I'll try to publish jicoco-config+jicoco-parent without jicoco to Maven Central, not sure if that's possible. What is `kotest-runner-console-jvm`? Kotest seems to have a mess of versions published to Central and I can't keep the jitpack-repo.
