### ISSUE TITLE
Java project can't import classes from 3.0-26-gf176d02

### ISSUE THREAD

**Issue by poliveira-fuze** [jitsi/ice4j#226]
On `pom.xml` I've added the following:
```
       <dependency>
            <groupId>org.jitsi</groupId>
            <artifactId>ice4j</artifactId>
            <version>3.0-24-g34c2ce5</version>
        </dependency>
```

The IDE is able to download the dependencies, I can check the existence of the JAR file at `~/.m2/repository/org/jitsi/ice4j` I even extracted the content of the JAR file and can see that contains some `.class` files under `org/jitsi` but somehow the maven and java cant import or compile with this version.

Is this happening for anyone else?

**Comment by poliveira-fuze** [comment]
Out of nowhere started to working. I will close.

**Comment by damencho** [comment]
Please use the community forum before opening new issues, thank you.

**Comment by poliveira-fuze** [comment]
@damencho Sure, I was thinking could be build/release problem. Apologies.
