### ISSUE TITLE
Java 17: issues with classes in org.ice4j.socket.jdk8

### ISSUE THREAD

**Issue by ibauersachs** [jitsi/ice4j#239]
I tried compiling ice4j with Java 17 and ran into issues with the stuff in org.ice4j.socket.jdk8. Java 16+ removed `--illegal-access=permit` and `sun.nio.ch.SelChImpl` is thus basically not available anymore.

I have a hard time to understand that code. I'm probably missing something, but if this is about filtering/redistributing incoming packets, why can't that be done with a regular (Server)SocketChannel? Is that code still needed at all?

@damencho thinks it's not needed anymore and was used when Jetty was serving web+tcp media. @bgrozev / @JonathanLennox ?

**Comment by bgrozev** [comment]
> @damencho thinks it's not needed anymore and was used when Jetty was serving web+tcp media

I concur that this is/was the only purpose of this code.

**Comment by ibauersachs** [comment]
@bgrozev can I interpret that as: the entire JDK8 package can be removed?

**Comment by bgrozev** [comment]
Yes.
