### ISSUE TITLE
Message decode offset error

### ISSUE THREAD

**Issue by yungtau** [jitsi/ice4j#50]
I found two issues in the project on 2014/11/24. Now one has been fixed, but another was ignored by me.

In this file "\src\main\java\org\ice4j\message\Message.java", the founktion "decode" line 1154 is "offset += (4 - (att.getDataLength() % 4));".
 I think it should be like this "offset += (4 - (att.getDataLength() % 4)) % 4;".

Because when the attribute's lenth is 0, the result was 4. but we need the offset += 0.
the ver. is SHA-1: 8b70299567f3062238a77877a01617e47e36d0de on 2015/12/3

**Comment by ibauersachs** [comment]
Line 1154 isn't executed because 0%4==0 on line 1152.

**Comment by yungtau** [comment]
I was too careless, because the other that caused an exception error in my program, it would not look carefully at the context. sorry!
