### ISSUE TITLE
Please consider tagging formal release

### ISSUE THREAD

**Issue by onlyjob** [jitsi/ice4j#52]
Formal releases are helpful for downstream package maintainers. Thanks.

**Comment by ibauersachs** [comment]
May I ask where/for whom you are packaging ice4j?

**Comment by onlyjob** [comment]
I'm not working on packaging (yet), I've just noticed that Ice4j is a prospective software for Debian as there is an [RFP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=698412) bug. 
Anyway [Software versioning](https://en.wikipedia.org/wiki/Software_versioning) is useful for number of reasons unrelated to packaging...

**Comment by ibauersachs** [comment]
I know this RFP and I'm working on it. The problem is the dependency on JAIN-SIP.

**Comment by onlyjob** [comment]
So what about versioning? And what's wrong with JAIN-SIP?

**Comment by ibauersachs** [comment]
None of the Jitsi projects (except for Jitsi itself) ever had a proper versioning scheme. They all just get 1.0.build-number. I'm not in control over this.

The javax.sip and javax.sdp packages of JAIN-SIP have a non-free license and thus cannot enter Debian. Search the dev mailing-list for details.

**Comment by onlyjob** [comment]
Thanks. I can't find anything relevant... If sip/sdp support is pluggable then maybe jain-sip don't have to be in Debian? Or perhaps it could go to "non-free" section...

**Comment by ibauersachs** [comment]
http://lists.jitsi.org/pipermail/dev/2015-November/025617.html

**Comment by onlyjob** [comment]
Thank you very much for context and all the best with the plan.

**Comment by ibauersachs** [comment]
I've released the current version of ice4j as 1.0 on Maven Central and it is tagged as that in Git. The next major/minor version will likely be when ice-lite is complete.

**Comment by onlyjob** [comment]
Thanks. :) Please consider _semantic versioning_:

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning
 * [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions)

**Comment by onlyjob** [comment]
Perhaps it is unnecessary to include `ice4j-` pat into tags. Just numbers and dots are fine.
