### ISSUE TITLE
Send command from webservice trhead socket client to socket server on android device

### ISSUE THREAD

**Issue by maforast** [jitsi/ice4j#57]
I have this problem: I have to request a device position through a SOAP webservice to a listening service on Android device through a socket.

On the Android device, there is a socket server service listening. The Android device's IP address for the socket connection is sent previously by a background service to a SOAP webservice listening on a server web. I implemented this scenario and it's working properly with WIFI network, but if I switch to an Internet GSM network, the socket is not open because the addresses of many operators are private and not public.

Is there a way to implement the same scenario?
I read about XMPP, ICE,TURN, etc. but I'm new to these technologies and I do not know if it's the right way.

**Comment by ibauersachs** [comment]
ICE can help you establishing a socket connection if the two endpoints are behind a NAT. But to start the negotiation in the first place, the client needs to have a permanent conection to the server (or do polling, use push-notifications, whatever).
This isn't an ice4j issue, your question is better addressed on e.g. StackOverflow or our mailing lists.
