### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by SStorm** [jitsi/ice4j#95]
Any plans on making a new release? Latest available in maven central is 1.0 which is very old - if you're relying on any new features / bugfixes since then (like me), you need to build and upload a version yourself, which is quite cumbersome to say the least...

**Comment by ibauersachs** [comment]
I didn't upload 1.1 because it accidentally introduced breaking API changes. So does 2.0 and AFAIK there's currently quite some development going on for it.
@bgrozev Any comment on when there might be a stable state that could go as 2.0 - and keeps the public API for the foreseeable future?
@damencho Can we upload the -SNAPSHOT builds to Maven Central too? (We have an account for Jenkins prepared that can upload snapshots only to org.jitsi)

**Comment by OrangeDog** [comment]
Could upload 1.1 as 2.0, and the current 2.0 can be 3.0?

**Comment by ibauersachs** [comment]
Current 2.0 was never released as such. Before I do a next release however, I want to have a plan for further releases.

**Comment by ibauersachs** [comment]
Proposal for future stable releases:

1. Switch to sematic versioning
2. Merge https://github.com/jitsi/ice4j/issues/95 to enforce 1.
3. Deploy snapshots to Maven Central (we have a Jenkins user for this)
4. Release whatever version used in a Jitsi Meet stable-combo-release also to Maven Central

@jitsi/developers please vote this comment with thumbs up/down (and leave comments).

**Comment by OrangeDog** [comment]
I assume you mean merge #123, not #95.

**Comment by ibauersachs** [comment]
@OrangeDog yes, edited, thanks!

**Comment by lecogiteur** [comment]
Hi,

I don't see new release from 2017. This project seems alive. Do you release it? When?

**Comment by bgrozev** [comment]
We just use the snapshots in our projects and haven't bothered with making a release.

**Comment by lecogiteur** [comment]
@bgrozev how to manage breaking change of library, we need to fork it?

**Comment by OrangeDog** [comment]
@bgrozev that is a foolish practice for your own projects, and very unhelpful for an open-source library.
While people can [lock their snapshots](https://www.mojohaus.org/versions-maven-plugin/examples/lock-snapshots.html), it still places a huge burden working out what's changed and which snapshots are safe to use.

**Comment by ibauersachs** [comment]
I had published the 1.0 a long time ago. We could never really agree on when to call 2.0 finished, so I never did another release to Maven Central. I can publish it again (or repeatedly) when someone tells me which commit to release. I haven't followed the development close enough to know when a version is stable enough to release.
As to what the Jitsi projects use (i.e. using the pinned snapshots), I don't like that very much either, but it's what it's done for the time being.

**Comment by ibauersachs** [comment]
> I don't think we can realistically release stable versions to maven as this takes time

It doesn't, this can actually be completely automated. But even manually I can do that if someone asks me to do so, e.g. after pushing a stable release to the Debian repo.

> API changes

The Maven build actually checks for API changes. It hasn't flagged anything because we've never done the 2.0 release.

**Comment by ibauersachs** [comment]
See #213
